# Generated by Django 5.0.7 on 2024-08-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('dosage', models.CharField(max_length=50)),
                ('quantity_options', models.JSONField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('concerns', models.JSONField()),
                ('key_benefits', models.JSONField()),
                ('how_to_use', models.JSONField()),
                ('precautions', models.JSONField()),
                ('faqs', models.JSONField()),
            ],
        ),
    ]
