# Generated by Django 5.0.7 on 2024-08-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyserverapp', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_description',
            new_name='incredients',
        ),
    ]
