# Generated by Django 5.0.7 on 2024-08-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyserverapp', '0005_doctorsinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsinfo',
            name='department',
            field=models.CharField(choices=[('sexologist', 'sexologist')], max_length=100),
        ),
    ]
