# Generated by Django 5.0.7 on 2024-08-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyserverapp', '0007_sliderimageshome_remove_doctorsinfo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='permission',
            field=models.BooleanField(default=True),
        ),
    ]
