# Generated by Django 5.0.7 on 2024-08-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyserverapp', '0008_product_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='permission',
            new_name='doctor_permission',
        ),
    ]
